-- ============================================================
-- (주)원스포츠 휘트니스센터 관리현황 - Supabase 초기 설정
-- Supabase Dashboard > SQL Editor에서 전체 실행하세요.
-- 운영 기록 시작일: 2026-09-01 (이전 날짜는 저장·조회하지 않음)
-- ============================================================

begin;

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  checklist jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inspections (
  id uuid primary key default gen_random_uuid(),
  inspection_date date not null default current_date,
  period text not null check (period in ('AM', 'PM')),
  area_id bigint not null references public.areas(id) on delete restrict,
  status text not null default 'normal' check (status in ('normal', 'issue', 'in_progress', 'completed')),
  checked_items text[] not null default '{}'::text[],
  item_statuses jsonb not null default '{}'::jsonb,
  note text not null default '',
  photo_paths text[] not null default '{}'::text[],
  manager_name text not null default '',
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inspection_date, period, area_id)
);

create table if not exists public.issues (
  id uuid primary key default gen_random_uuid(),
  category text not null default 'other' check (category in ('facility', 'safety', 'cleaning', 'complaint', 'other')),
  area_id bigint references public.areas(id) on delete set null,
  title text not null check (char_length(title) between 1 and 120),
  description text not null,
  status text not null default 'received' check (status in ('received', 'reviewing', 'in_progress', 'completed')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  received_date date not null default current_date,
  due_date date,
  action_note text not null default '',
  photo_paths text[] not null default '{}'::text[],
  is_public boolean not null default true,
  manager_name text not null default '',
  completed_at timestamptz,
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventories (
  id uuid primary key default gen_random_uuid(),
  record_date date not null default current_date,
  area_id bigint references public.areas(id) on delete set null,
  category text not null default 'other' check (category in ('facility', 'equipment', 'supply', 'other')),
  name text not null check (char_length(name) between 1 and 120),
  quantity text not null default '',
  status text not null default 'normal' check (status in ('normal', 'low', 'restocking', 'repair')),
  note text not null default '',
  photo_paths text[] not null default '{}'::text[],
  is_public boolean not null default true,
  manager_name text not null default '',
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 운영 시작일 고정

delete from public.inspections where inspection_date < date '2026-09-01';
delete from public.issues where received_date < date '2026-09-01';
delete from public.inventories where record_date < date '2026-09-01';

alter table public.inspections alter column inspection_date set default greatest(current_date, date '2026-09-01');
alter table public.issues alter column received_date set default greatest(current_date, date '2026-09-01');
alter table public.inventories alter column record_date set default greatest(current_date, date '2026-09-01');

alter table public.inspections drop constraint if exists inspections_operational_date_check;
alter table public.inspections add constraint inspections_operational_date_check check (inspection_date >= date '2026-09-01');

alter table public.issues drop constraint if exists issues_operational_date_check;
alter table public.issues add constraint issues_operational_date_check check (received_date >= date '2026-09-01');

alter table public.inventories drop constraint if exists inventories_operational_date_check;
alter table public.inventories add constraint inventories_operational_date_check check (record_date >= date '2026-09-01');

create index if not exists inspections_date_idx on public.inspections (inspection_date desc);
create index if not exists inspections_area_period_idx on public.inspections (area_id, period);
create index if not exists issues_received_date_idx on public.issues (received_date desc);
create index if not exists issues_category_status_idx on public.issues (category, status);
create index if not exists inventories_record_date_idx on public.inventories (record_date desc);
create index if not exists inventories_category_status_idx on public.inventories (category, status);

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins a
    where a.user_id = auth.uid()
      and a.active = true
  );
$$;

revoke all on function public.is_app_admin() from public;
grant execute on function public.is_app_admin() to anon, authenticated;

create or replace function public.set_management_updated_fields()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  if tg_table_name = 'issues' then
    if new.status = 'completed' and (old.status is distinct from 'completed' or old.completed_at is null) then
      new.completed_at = now();
    elsif new.status <> 'completed' then
      new.completed_at = null;
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.set_area_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inspections_set_updated_fields on public.inspections;
create trigger inspections_set_updated_fields
before update on public.inspections
for each row execute function public.set_management_updated_fields();

drop trigger if exists issues_set_updated_fields on public.issues;
create trigger issues_set_updated_fields
before update on public.issues
for each row execute function public.set_management_updated_fields();

drop trigger if exists inventories_set_updated_fields on public.inventories;
create trigger inventories_set_updated_fields
before update on public.inventories
for each row execute function public.set_management_updated_fields();

drop trigger if exists areas_set_updated_at on public.areas;
create trigger areas_set_updated_at
before update on public.areas
for each row execute function public.set_area_updated_at();

insert into public.areas (slug, name, sort_order, checklist, active)
values
  ('lobby', '로비', 1, '["바닥·출입구 청결", "안내물·비품 정리", "조명 상태", "특이사항 확인"]'::jsonb, true),
  ('fitness', '헬스장', 2, '["운동기구 작동 상태", "바닥·기구 청결", "안전 상태", "환기·온도", "원판·소도구 정리"]'::jsonb, true),
  ('golf', '골프연습장', 3, '["타석·스크린 작동", "안전망·매트 상태", "바닥 청결", "골프용품 정리", "조명·환기"]'::jsonb, true),
  ('screen-golf-1', '스크린골프장 1번', 4, '["기기 전원·작동", "타석·센서 상태", "매트·타석 청결", "골프채·비품 정리", "조명·환기"]'::jsonb, true),
  ('screen-golf-2', '스크린골프장 2번', 5, '["기기 전원·작동", "타석·센서 상태", "매트·타석 청결", "골프채·비품 정리", "조명·환기"]'::jsonb, true),
  ('screen-golf-3', '스크린골프장 3번', 6, '["기기 전원·작동", "타석·센서 상태", "매트·타석 청결", "골프채·비품 정리", "조명·환기"]'::jsonb, true),
  ('gx', 'GX룸', 7, '["바닥·거울 청결", "음향기기 작동", "운동용품 정리", "조명·환기", "안전 상태"]'::jsonb, true),
  ('pilates', '기구필라테스룸', 8, '["리포머·기구 상태", "바닥·거울 청결", "소도구 정리", "조명·환기", "안전 상태"]'::jsonb, true),
  ('table-tennis', '탁구장', 9, '["탁구대·네트 상태", "라켓·공 비품", "바닥 청결", "조명 상태", "주변 정리"]'::jsonb, true),
  ('mens-locker', '남자 탈의실', 10, '["락커·바닥 청결", "샤워시설·배수", "드라이기·비품", "악취·환기", "안전 상태"]'::jsonb, true),
  ('womens-locker', '여자 탈의실', 11, '["락커·바닥 청결", "샤워시설·배수", "드라이기·비품", "악취·환기", "안전 상태"]'::jsonb, true),
  ('restroom', '화장실', 12, '["변기·세면대 청결", "휴지·비누 보충", "배수 상태", "악취·환기", "조명 상태"]'::jsonb, true),
  ('reading-room', '독서실', 13, '["책상·의자 정리", "바닥 청결", "조명 상태", "냉난방·환기", "소음·이용환경"]'::jsonb, true)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  checklist = excluded.checklist,
  active = excluded.active;

alter table public.app_admins enable row level security;
alter table public.areas enable row level security;
alter table public.inspections enable row level security;
alter table public.issues enable row level security;
alter table public.inventories enable row level security;

revoke all on table public.app_admins from anon, authenticated;
revoke all on table public.areas from anon, authenticated;
revoke all on table public.inspections from anon, authenticated;
revoke all on table public.issues from anon, authenticated;
revoke all on table public.inventories from anon, authenticated;

grant select on table public.areas to anon, authenticated;
grant select on table public.inspections to anon, authenticated;
grant select on table public.issues to anon, authenticated;
grant select on table public.inventories to anon, authenticated;
grant select on table public.app_admins to authenticated;
grant insert, update, delete on table public.inspections to authenticated;
grant insert, update, delete on table public.issues to authenticated;
grant insert, update, delete on table public.inventories to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists app_admins_self_read on public.app_admins;
create policy app_admins_self_read on public.app_admins for select to authenticated using (user_id = auth.uid());

drop policy if exists areas_public_read on public.areas;
create policy areas_public_read on public.areas for select to anon using (active = true);

drop policy if exists areas_authenticated_read on public.areas;
create policy areas_authenticated_read on public.areas for select to authenticated using (active = true or public.is_app_admin());

drop policy if exists inspections_public_read on public.inspections;
create policy inspections_public_read on public.inspections for select to anon, authenticated using (inspection_date >= date '2026-09-01');

drop policy if exists inspections_admin_insert on public.inspections;
create policy inspections_admin_insert on public.inspections for insert to authenticated with check (public.is_app_admin() and inspection_date >= date '2026-09-01');

drop policy if exists inspections_admin_update on public.inspections;
create policy inspections_admin_update on public.inspections for update to authenticated using (public.is_app_admin() and inspection_date >= date '2026-09-01') with check (public.is_app_admin() and inspection_date >= date '2026-09-01');

drop policy if exists inspections_admin_delete on public.inspections;
create policy inspections_admin_delete on public.inspections for delete to authenticated using (public.is_app_admin());

drop policy if exists issues_public_read on public.issues;
create policy issues_public_read on public.issues for select to anon using (is_public = true and received_date >= date '2026-09-01');

drop policy if exists issues_authenticated_read on public.issues;
create policy issues_authenticated_read on public.issues for select to authenticated using (received_date >= date '2026-09-01' and (is_public = true or public.is_app_admin()));

drop policy if exists issues_admin_insert on public.issues;
create policy issues_admin_insert on public.issues for insert to authenticated with check (public.is_app_admin() and received_date >= date '2026-09-01');

drop policy if exists issues_admin_update on public.issues;
create policy issues_admin_update on public.issues for update to authenticated using (public.is_app_admin() and received_date >= date '2026-09-01') with check (public.is_app_admin() and received_date >= date '2026-09-01');

drop policy if exists issues_admin_delete on public.issues;
create policy issues_admin_delete on public.issues for delete to authenticated using (public.is_app_admin());

drop policy if exists inventories_public_read on public.inventories;
create policy inventories_public_read on public.inventories for select to anon using (is_public = true and record_date >= date '2026-09-01');

drop policy if exists inventories_authenticated_read on public.inventories;
create policy inventories_authenticated_read on public.inventories for select to authenticated using (record_date >= date '2026-09-01' and (is_public = true or public.is_app_admin()));

drop policy if exists inventories_admin_insert on public.inventories;
create policy inventories_admin_insert on public.inventories for insert to authenticated with check (public.is_app_admin() and record_date >= date '2026-09-01');

drop policy if exists inventories_admin_update on public.inventories;
create policy inventories_admin_update on public.inventories for update to authenticated using (public.is_app_admin() and record_date >= date '2026-09-01') with check (public.is_app_admin() and record_date >= date '2026-09-01');

drop policy if exists inventories_admin_delete on public.inventories;
create policy inventories_admin_delete on public.inventories for delete to authenticated using (public.is_app_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('management-photos', 'management-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists management_photos_public_read on storage.objects;
create policy management_photos_public_read on storage.objects for select to public using (bucket_id = 'management-photos');

drop policy if exists management_photos_admin_insert on storage.objects;
create policy management_photos_admin_insert on storage.objects for insert to authenticated with check (bucket_id = 'management-photos' and public.is_app_admin());

drop policy if exists management_photos_admin_update on storage.objects;
create policy management_photos_admin_update on storage.objects for update to authenticated using (bucket_id = 'management-photos' and public.is_app_admin()) with check (bucket_id = 'management-photos' and public.is_app_admin());

drop policy if exists management_photos_admin_delete on storage.objects;
create policy management_photos_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'management-photos' and public.is_app_admin());

alter table public.inspections replica identity full;
alter table public.issues replica identity full;
alter table public.inventories replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'inspections') then
    alter publication supabase_realtime add table public.inspections;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'issues') then
    alter publication supabase_realtime add table public.issues;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'inventories') then
    alter publication supabase_realtime add table public.inventories;
  end if;
end $$;

commit;

-- 관리자 등록 예시
-- insert into public.app_admins (user_id, display_name, active)
-- select id, '장지연', true
-- from auth.users
-- where email = '관리자이메일@example.com'
-- on conflict (user_id) do update set display_name = excluded.display_name, active = true;
